### ISSUE TITLE
Missing PegGame.py !!!

### ISSUE THREAD

**Issue by AlkisPis** [gustavo-sopena/Peg-Solitaire#1]
'main.py' imports 'PegGame.py'. Where is this file in the package??? It's not even in the Web!

**Comment by gustavo-sopena** [comment]
'main.py' has been updated to address this issue

21930c8c1ab5666240383ec961bd26807e4f0cb5

**Comment by AlkisPis** [comment]
'PegGame.py' was missing and this is said to be "fixed" by importing 'xlsxwriter', a 45MB package, containing 2,650  files!!
That is, the issue is "fixed" by creating a much bigger issue!
